spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huawei_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: yanyuqinghe